#!/bin/sh

# debug level = 1 for only output logs with INFO or higher level, 0 for output DEBUG logs.
if [ "x${QLIVE_LOG_DEBUG}" = "x" ]; then QLIVE_DEBUG_LEVEL=1; else QLIVE_DEBUG_LEVEL=0; fi
if [ "x${QLIVE_CONFIG_FILENAME}" = "x" ]; then QLIVE_CONFIG_FILENAME="qlive.conf"; fi
if [ "x${QLIVE_HTTP_LISTEN_ADDR}" = "x" ]; then QLIVE_HTTP_LISTEN_ADDR=":8080"; fi
if [ "x${QLIVE_WS_LISTEN_ADDR}" = "x" ]; then QLIVE_WS_LISTEN_ADDR=":8082"; fi
if [ "x${QLIVE_MONGODB_URI}" = "x" ]; then QLIVE_MONGODB_URI="mongodb://127.0.0.1:27017"; fi
if [ "x${QLIVE_MONGODB_DATABASE}" = "x" ]; then QLIVE_MONGODB_DATABASE="qrtc_qlive"; fi

echo "render config file ${QLIVE_CONFIG_FILENAME}"
sed -i -e "s@__DEBUG_LEVEL__@${QLIVE_DEBUG_LEVEL}@g"  ${QLIVE_CONFIG_FILENAME}
sed -i -e "s@__HTTP_LISTEN_ADDR__@${QLIVE_HTTP_LISTEN_ADDR}@g"  ${QLIVE_CONFIG_FILENAME}
sed -i -e "s@__WS_LISTEN_ADDR__@${QLIVE_WS_LISTEN_ADDR}@g"  ${QLIVE_CONFIG_FILENAME}
sed -i -e "s@__MONGODB_URI__@${QLIVE_MONGODB_URI}@g" ${QLIVE_CONFIG_FILENAME}
sed -i -e "s@__MONGODB_DATABASE__@${QLIVE_MONGODB_DATABASE}@g" ${QLIVE_CONFIG_FILENAME}
sed -i -e "s@__QINIU_SMS_ACCESS_KEY__@${QINIU_ACCESS_KEY}@g" ${QLIVE_CONFIG_FILENAME}
sed -i -e "s@__QINIU_SMS_SECRET_KEY__@${QINIU_SECRET_KEY}@g" ${QLIVE_CONFIG_FILENAME}
sed -i -e "s@__QINIU_SMS_SIGN_ID__@${QINIU_SMS_SIGN_ID}@g"  ${QLIVE_CONFIG_FILENAME}
sed -i -e "s@__QINIU_SMS_TEMP_ID__@${QINIU_SMS_TEMP_ID}@g" ${QLIVE_CONFIG_FILENAME}
sed -i -e "s@__QINIU_RTC_APP_ID__@${QINIU_RTC_APP_ID}@g" ${QLIVE_CONFIG_FILENAME}
sed -i -e "s@__QINIU_RTC_ACCESS_KEY__@${QINIU_ACCESS_KEY}@g" ${QLIVE_CONFIG_FILENAME}
sed -i -e "s@__QINIU_RTC_SECRET_KEY__@${QINIU_SECRET_KEY}@g" ${QLIVE_CONFIG_FILENAME}
sed -i -e "s@__QINIU_LIVE_PUBLISH_HOST__@${QINIU_LIVE_PUBLISH_HOST}@g" ${QLIVE_CONFIG_FILENAME}
sed -i -e "s@__QINIU_LIVE_PUBLISH_HUB__@${QINIU_LIVE_PUBLISH_HUB}@g" ${QLIVE_CONFIG_FILENAME}
sed -i -e "s@__RONGCLOUD_APP_KEY__@${RONGCLOUD_APP_KEY}@g" ${QLIVE_CONFIG_FILENAME}
sed -i -e "s@__RONGCLOUD_APP_SECRET__@${RONGCLOUD_APP_SECRET}@g" ${QLIVE_CONFIG_FILENAME}
echo "rendering config file ${QLIVE_CONFIG_FILENAME} done"
echo "execute :$@"
exec "$@"